theme: jekyll-theme-slate
title: Technical Diary of a Dummy
description: Thoughts and Opinions that will live on after they have vacated my brain.

email: james.a.land10@gmail.com
github_username: jaland

# Google Analytics
google_analytics: G-CM1B1M527E